// Lessons. Each step either waits for a chord ({ play: [degree, dir] }),
// waits for something in the app ({ wait: 'thing' }), or just needs a tap.
// {1u}-style tokens are replaced with the real chord name in the current key.

export const LESSONS = [
  {
    id: 'pop4',
    title: 'The four chords behind half of pop',
    blurb: '1, 5, 6, 4. You will recognise it instantly.',
    intro: "Here's the secret that annoys music snobs: a huge pile of pop songs use the same four chords. Let It Be. Don't Stop Believin'. Someone Like You. With or Without You. In Nashville numbers they're 1, 5, 6, 4. Follow the glowing button, and let each chord ring for a moment.",
    steps: [
      { play: [1, 'c'], say: 'Start at home. Press 1.' },
      { play: [5, 'c'], say: 'Now 5. It wants to go somewhere.' },
      { play: [6, 'c'], say: '6. The minor one, a little bittersweet.' },
      { play: [4, 'c'], say: '4. And it rolls back toward home.' },
      { play: [1, 'c'], say: 'Again. Slower this time, count four in your head on each chord.' },
      { play: [5, 'c'], say: '5.' },
      { play: [6, 'c'], say: '6.' },
      { play: [4, 'c'], say: '4.' },
      { wait: 'key', say: 'Now tap KEY to change key. Same buttons, same feel, different key. That is the whole point of numbers instead of chord names.', highlight: 'key' },
      { play: [1, 'c'], say: '1, in your new key.' },
      { play: [5, 'c'], say: '5.' },
      { play: [6, 'c'], say: '6.' },
      { play: [4, 'c'], say: '4.' },
    ],
    outro: "That's the backbone of a frankly embarrassing amount of the radio. Try it again with the ARP on and it instantly sounds like a song.",
  },
  {
    id: 'sad',
    title: 'The sad version',
    blurb: 'Same chords, start on 6. Instant feelings.',
    intro: "Same four chords as before, but start on the 6 instead of the 1. Starting on a minor chord changes what your ear thinks home is, so the whole thing turns moody. Zombie by The Cranberries lives here. So does Despacito, which is funny if you think about it.",
    steps: [
      { play: [6, 'c'], say: 'Start on 6.' },
      { play: [4, 'c'], say: '4.' },
      { play: [1, 'c'], say: '1. Notice it does not feel like home anymore.' },
      { play: [5, 'c'], say: '5. And it pulls you back to the 6.' },
      { wait: 'preset:keys', say: 'Tap SOUND until you get Electric Piano. Late-night mode.', highlight: 'sound' },
      { play: [6, 'c'], say: '6.' },
      { play: [4, 'c'], say: '4.' },
      { play: [1, 'c'], say: '1.' },
      { play: [5, 'c'], say: '5.' },
    ],
    outro: 'Happy song: 1 5 6 4. Sad song: 6 4 1 5. Same chords, different starting point. Most of songwriting is tricks like this.',
  },
  {
    id: 'dreamy',
    title: 'Making it dreamy with the joystick',
    blurb: '7ths and 9ths. Where the sunset sound lives.',
    intro: 'Plain chords are fine. Sevenths and ninths are where the dreamy stuff lives. Hold the joystick in a direction first, then press the chord. The screen tells you what you made.',
    steps: [
      { play: [1, 'c'], say: 'Plain 1 first, so you know where we started.' },
      { play: [1, 'u'], say: 'Push the stick up and press 1. That is {1u}. Softer, a bit wistful.' },
      { play: [4, 'u'], say: 'Stick up, press 4. {4u}.' },
      { play: [1, 'ur'], say: 'Up-right on 1: {1ur}. A 9th chord. This is the sound of every sunset in a video game.' },
      { play: [4, 'ur'], say: 'Up-right on 4: {4ur}.' },
      { play: [6, 'u'], say: 'Up on 6: {6u}.' },
      { play: [5, 'r'], say: 'Right on 5: {5r}. Right adds the 9 without the 7. Lighter, more open.' },
      { say: 'Now hold 1 down and slowly roll the stick around while you hold it. The chord morphs without restarting. Tap Next when you have had your fun.', next: true },
    ],
    outro: 'Rule of thumb: when something sounds too plain, push the stick up. When it sounds too sweet, try down.',
  },
  {
    id: 'layers',
    title: 'Building a song in layers',
    blurb: 'Chords, then drums, then arp. Then the drop.',
    intro: "This is exactly how the track in that video works. It starts small, adds one layer at a time, then pulls everything out and drops it all back in at once. The drop is the trick. Let's build one.",
    steps: [
      { wait: 'preset:pad', say: 'Pick the Warm Pad with SOUND. It is the cushion everything else sits on.', highlight: 'sound' },
      { wait: 'loop:recorded', say: 'Tap REC. You get a count-in. On the first beat, play 1, 5, 6, 4, holding each for four clicks. Then tap REC again to close the loop.', highlight: 'rec', guide: [[1, 'c'], [5, 'c'], [6, 'c'], [4, 'c']] },
      { wait: 'drums:on', say: 'Your chords are looping now. Layer two: turn on the drums. The 80s kit with the Drive beat is very on-theme.', highlight: 'drums' },
      { wait: 'preset:pluck', say: 'Switch the sound to Pluck. The loop keeps its pad, the new sound is just for your hands.', highlight: 'sound' },
      { wait: 'arp:on', say: 'Turn the ARP on. UP is a good start. Now a held chord plays its notes one at a time, locked to the drums.', highlight: 'arp' },
      { play: [1, 'c'], say: 'Play along with your loop. 1...' },
      { play: [5, 'c'], say: '5...' },
      { play: [6, 'c'], say: '6...' },
      { play: [4, 'c'], say: '4.' },
      { wait: 'drop:out', say: 'Now the trick. Tap DROP. Drums and loop vanish and only your arp is left. Hang there for a bar or two. Feel the tension building?', highlight: 'drop' },
      { wait: 'drop:in', say: 'Tap DROP again. Everything slams back in on the next bar line. That moment is the one in the video that gives you goosebumps.', highlight: 'drop' },
    ],
    outro: 'Add layers, take them away, bring them all back at once. That is a huge part of electronic music, and you just did it on a free app.',
  },
  {
    id: 'sus',
    title: 'Tension and release with sus chords',
    blurb: 'Make a question, then answer it.',
    intro: 'A sus chord swaps the 3rd for a 4th or a 2nd. It sounds unfinished, like a question. Going back to the plain chord answers it. Rock bands, worship bands and film composers all lean on this constantly.',
    steps: [
      { play: [1, 'l'], say: 'Push the stick left and hold 1. That is {1l}. Just hang on it.' },
      { play: [1, 'c'], say: 'Keep holding 1 and let go of the stick. Hear it settle? That is resolution.' },
      { play: [5, 'l'], say: 'Same thing on 5. Stick left, press 5: {5l}.' },
      { play: [5, 'c'], say: 'Let the stick go.' },
      { play: [1, 'c'], say: 'And home to 1. Very satisfying.' },
      { play: [4, 'ul'], say: 'Up-left is sus2, the airy cousin: {4ul}.' },
      { play: [4, 'c'], say: 'Resolve it.' },
      { play: [5, 'l'], say: 'One more, the big ending move: {5l}, wait for it...' },
      { play: [5, 'c'], say: '...resolve to {5c}...' },
      { play: [1, 'c'], say: '...and land on 1.' },
    ],
    outro: 'Tension, then release. Make people wait a little and the payoff feels bigger. Works in music, works in arguments.',
  },
  {
    id: 'lofi',
    title: 'A lo-fi beat from scratch',
    blurb: 'Jazzy chords, lazy drums, slightly broken sound.',
    intro: "Lo-fi is mostly three things: jazzy chords, a lazy beat, and sound that's a little bit broken on purpose. Let's make one from nothing.",
    steps: [
      { wait: 'preset:lofi', say: 'Set the sound to Lo-Fi Tape. The wobble is on purpose.', highlight: 'sound' },
      { wait: 'tempo:70-90', say: 'Bring the tempo down to somewhere between 70 and 90. Lo-fi is never in a hurry.', highlight: 'tempo' },
      { wait: 'kit:lofi', say: 'Pick the Lo-Fi drum kit.', highlight: 'kit' },
      { wait: 'beat:boombap', say: 'Choose the Boom Bap beat.', highlight: 'beat' },
      { wait: 'drums:on', say: 'And turn the drums on.', highlight: 'drums' },
      { play: [4, 'ur'], say: 'Lo-fi lives on 7ths and 9ths. Up-right on 4: {4ur}.' },
      { play: [3, 'u'], say: 'Up on 3: {3u}.' },
      { play: [2, 'ur'], say: 'Up-right on 2: {2ur}.' },
      { play: [1, 'u'], say: 'Up on 1: {1u}. Home.' },
      { wait: 'loop:recorded', say: 'Now record those four as a loop: REC, count-in, one bar each, REC again.', highlight: 'rec', guide: [[4, 'ur'], [3, 'u'], [2, 'ur'], [1, 'u']] },
    ],
    outro: 'That is a lo-fi beat. Headphones on, pretend it is raining, and play little single notes over it with the arp on RAND.',
  },
];

export const TIPS = [
  'Hold the joystick up before you press a chord to make it a 7th. Instant mood.',
  'Every button is in key. There are no wrong notes here, only interesting ones.',
  '1, 5, 6, 4 is the most-used progression in pop. Try 6, 4, 1, 5 for the sad version.',
  'The DROP button cuts the drums and loop. Tap it again and everything comes back on the next bar.',
  'Slow the tempo to 75 and pick Lo-Fi Tape. That is a whole genre right there.',
  'Arpeggiator on UP plus the Pluck sound is the fastest way to sound like a video game.',
  'Sus chords (stick left) sound like a question. Let the stick go to answer it.',
  'Record a loop with the Warm Pad, then switch sounds. The loop keeps its sound.',
  'Down on the joystick flips major and minor. Try it on 4 for a classic bittersweet move.',
  'The key does not matter much on its own. Pick one that feels good and stay there.',
  'When in doubt: fewer chords, held longer.',
  'Headphones make the reverb and stereo delay sound twice as expensive.',
];

export function tipOfTheDay(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const day = Math.floor((date - start) / 86400000);
  return TIPS[day % TIPS.length];
}
